name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      
      - name: Tests
        run: make && cd bin && ./test.exe && cd ../ && make clean
      
      - name: Check codestyle
        run: git ls-files *.{cpp,h} | xargs clang-format -i --verbose && git diff --exit-code

      - name: Build application
        run: make
